export default function handleError(e) {
    throw e
}